### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by MaximalesGaming** [NathanKell/ModularFuelSystem#166] opened 2017-01-03 22:45 UTC
When I'm starting KSP with the newest version of RealFules (downloaded and installed by CKAN) with the "Stockalike RF Configs" config, I have some problems with the animations of the thrust from the RCS-Thruster, modded and stock engines.

My problem:
The game shows me the animation of running RCS-Thruster and running engines, but the thrusters and the engines aren't activated. Same effect with other engines and thruster. 

First I htought it is a download issue or a loading problem. After a re-install of KSP and more than 10 re-downloads of the mod, I gave up.

Hopefully anyone can help me.

Greetings from Germany

**Comment by blowfishpro** [comment] 2017-01-03 23:46
RCS is this issue: https://github.com/Raptor831/RFStockalike/issues/76

**Comment by MaximalesGaming** [comment] 2017-01-04 00:36
I'm using:
Alternate Resource Panel
BetterBurn Time
Chatterer
Community Resource Pack
Docking Port Sound FX
Engine Lighting
EVA Parachutes & Ejection Seats
HullcamVDS Continued
Kerbal Engineer Redux
KSP AVC
KW Rocketry (with Graduated Power Response Config)
MechJeb 2
MechJeb and Engineer for all!
Modular Rocket Systems
ModularFlightIntegrator
Module Manager
Real Fuels (with Stockalike RF Config)
Real Plume (with Stock Config)
Real Chute Parachute Systems
Reentry Particle Effect
Ship Effects-Sound-Mod: Dynamic Sound Effects
Smoke Screen - Extended FX Plugin
Solver Engines plugin
SpaceY Expanded
SpaceY Heavy Lifter
Toolbar
Water Sounds

In the Picture the Engine is in "deactivated" mode.
![issue_realfuels](https://cloud.githubusercontent.com/assets/17008430/21628216/02f2ab18-d21e-11e6-864a-3ecf70cfb4b7.jpg)

**Comment by blowfishpro** [comment] 2017-01-04 00:39
Could you upload KSP's log and also say which engine that is (or whether it happens for all engines)?

**Comment by MaximalesGaming** [comment] 2017-01-04 00:50
This is an efdect of every engine in the game (modded and sock). I'll send the ksp log later because I've already shut down my computer and in germany it is 2 o'clock in the morning.

**Comment by blowfishpro** [comment] 2017-01-04 05:10
Oh, also is this only for the first couple of seconds when you load the scene or continuously.  Because if it's only the first couple of seconds I already reproduced.

Actually, taking a second look at your mod list, I don't think you should have RealPlume-Stock.  RF stockalike comes with its own RealPlume configs which should be installed but will likely conflict with RealPlume-Stock

**Comment by MaximalesGaming** [comment] 2017-01-04 13:34
So now I have removed the Real Plume Config but now modded engines and RCS Thruster have a thrust animation but they are disabled or habe 0% thrust.
![issue_realfuels_02](https://cloud.githubusercontent.com/assets/17008430/21643856/e1968918-d28a-11e6-838f-45d672637024.jpg)

**Comment by blowfishpro** [comment] 2017-01-04 17:42
Can we try to talk about the different problems here separately?  Here are the problems I am aware of

* RCS effects always show even when not thrusting.  This is a known issue with the RF stockalike configs that has already been fixed in their development version.  Nothing RF can do about this
* For engines with multiple configs, other configs' effects will play for the first couple of seconds when you enter the scene.  Once the scene loads they behave normally.  This looks like it might be an RF issue but I haven't been able to determine the cause yet.

Are you seeing any issues which are **different** than the above?  And can you please try to test using specific engines and state which engines they are? (and for these purposes you should test using stock engines - if there's an issue with a modded engine that doesn't show on stock engines then that's probably an issue with RF Stockalike and not RF itself).

I'd like to help but you're giving me very little information to go on here.

**Comment by blowfishpro** [comment] 2017-01-04 17:44
Oh, and if the answer to the above is yes that you are still seeing issues other than those, **please** include your log.  Just for future reference, logs should be included with every support request and possible bug report.

**Comment by MaximalesGaming** [comment] 2017-01-04 18:30
I have tested a lot engines now in the last half hour.
These Engines have animation issues:
-"Hound" engine (Modular Rocket Systems
-MRS Jet Engine (Modular Rocket Systems
-Xenon engine (Stock)
-Atomic engine (Stock)

NO more Problems. Do you need the KSP-LOG??

![stock engines test](https://cloud.githubusercontent.com/assets/17008430/21653928/b903901c-d2b3-11e6-898f-cba0f4c3713b.jpg)
![modular rocket systems engines check](https://cloud.githubusercontent.com/assets/17008430/21653929/b928609a-d2b3-11e6-981a-d44865824767.jpg)

**Comment by blowfishpro** [comment] 2017-01-04 18:49
Logs can always help identify problems.

Exactly what are the animation issues?  Specifically what do you see on the stock engines?

**Comment by MaximalesGaming** [comment] 2017-01-04 19:03
When I see the engines like this, it seems like they are running but throttle is 0% or no fuel is remaining (You can see it in the Picture).
[KSP.txt](https://github.com/NathanKell/ModularFuelSystem/files/685595/KSP.txt)
![stock engines test_2](https://cloud.githubusercontent.com/assets/17008430/21655088/ce36c972-d2b8-11e6-83f1-4a6d36df0084.jpg)

**Comment by blowfishpro** [comment] 2017-01-04 22:19
Ok, I can go on that now.  I will look when I get home.

**Comment by blowfishpro** [comment] 2017-01-05 01:36
I've confirmed the issue but also that it has to do with RF Stockalike's RealPlume configs and not with RF itself.  As far as engines are concerned, RealFuels is just a framework, it doesn't make any changes to any engines by itself.  Any issues with specific engines are probably the fault of whatever mod is configuring the engines, in this case RF Stockalike.

The two stock engines are a quick fix, so I'll try to just create a PR to fix them and submit it over there.  If you see the same issue with any modded engines, you should probably report it at that repository.

**Closed by blowfishpro** 2017-01-05 01:36 UTC
