### ISSUE TITLE
RF and TweakScale causing negative part mass.

### ISSUE THREAD

**Issue by RobynNailo** [NathanKell/ModularFuelSystem#165] opened 2016-12-27 22:30 UTC
When I create a 1.25m fuel tank (was early in career so didn't test anything bigger) then resizing it down I was left with a part with negative mass. Tried on a fresh install with only RealFuels, RF dependencies, RF stockalike engine configs, and TweakScale. When right clicking the mass seems to be correct, but the engineer's report and middle click show the negative mass. When launched the part displays the odd behavior of a negative mass part.

So I can't tell 100% which is causing the issue, I was trying to dig into the code and I think it might be RF, possibly around the figuring out the massdelta stage. Wasn't able to find myself anywhere else in TweakScale or RF where a negative might be introduced, though my coding is pretty rusty.

**Comment by blowfishpro** [comment] 2016-12-29 01:16
@NathanKell is the RF-Tweakscale project supposed to be included in the solution?

**Comment by Starwaster** [comment] 2017-02-18 00:51
@blowfishpro 
@pellinor0

Ok, so I see that we still have this open TweakScale issue and someone complaining in the forums about negative mass issues, which are easily confirmed.

The problem is clearly that both mods are setting mass via GetModuleMass() and only one of them should be. And that one should be ModuleFuelTanks (present in both MFS/RF). It *could* be  fixed on our side by detecting tweak scale and crippling the code that sets tank mass on our side but that defeats part of the purpose of having RF in the first place (realistic mass and cost instead of stock)

What we need is some sort of Tweak Scale exemption from mass and cost setting and let ModuleFuelTanks handle it instead.

**Comment by pellinor0** [comment] 2017-02-18 11:54
I patched the TweakScale module to not touch mass when MFT is present: https://github.com/pellinor0/TweakScale/commit/5ddb03a6b2ee3b0dc84d541926a42d4fb2cdf49b

**Closed** 2019-01-12 02:54 UTC
