### ISSUE TITLE
DLL compiles in master and function of TestflightRF.dll

### ISSUE THREAD

**Issue by Bornholio** [NathanKell/ModularFuelSystem#212] opened 2018-09-02 23:26 UTC
First question is there a reason there is not .dll in master?

Second what is the proper way to deal with RF vs Test flight changes  for https://github.com/KSP-RO/TestFlight/pull/182

**Comment by blowfishpro** [comment] 2018-09-03 17:54
There are legimate reasons to not include compiled DLLs in the repo:

* It makes it difficult for more than one person to work on the project at once.  You are forced to either rebase every commit right before merging, or do a manual merge with a recompile.
* The compiled plugin is really a product of the code in the repo rather than the code itself.  For any particular commit, the plugin can be reproduced by compiling it, so there's no point in committing it.
  * Admittedly, this probably makes more sense if you have some sort of continuous integration automatically compiling on every push.  I've set this up for other plugin mods but there are a lot of dependencies and configuration that I'm not sure it makes sense to add to RF

**Comment by jwvanderbeck** [comment] 2018-09-03 19:37
Compatibility with TF is handled externally rather than internally.  This was an important design choice made so that TF itself wouldn't need constant updates to maintain compatibility with other mods.  TF publishes an API that RF then uses to make itself compatible with TF.  This is done by RF in the TestFlightRF plugin.  There should be no need of any changes unless either the TF API changes or the RF implementation has a bug or you simply want to add new features.

**Comment by taniwha** [comment] 2018-10-23 06:44
I wonder if I should create a "will not break" tag...
Closing because dlls do not belong in version control.

**Closed by taniwha** 2018-10-23 06:44 UTC
