### ISSUE TITLE
KSP 1.4.5 and 1.6.0

### ISSUE THREAD

**Issue by raidernick** [NathanKell/ModularFuelSystem#215] opened 2018-12-23 07:10 UTC
@blowfishpro @Starwaster would either of you mind updating this for 1.4.5 to properly index in ckan so I can finally release RO for that ksp verison(it should be a simple recompile as 1.4.3 is pretty much the same). This is among 3 mods holding it up for that. Then I want to look at 1.6 for RO and skip 1.5.1, I would like RF to possibly be look at 1.6 after that.

**Comment by Starwaster** [comment] 2018-12-23 08:33
There's one thing I want to do to RF before this happens regarding thermal analytic. (specifically, need to ensure that part.analyticInternalInsulationFactor is set properly. Apparently the way this is handled by KSP doesn't result in a realistic heating rate during analytic mode. (it adjusts how quickly FI lerps between temperature values but it's not based on game time passage and it's static between different time warp rates.

@blowfishpro if you think you can work out what to do about that before I can get to it, feel free. But I would like to to get it done before we update next.

(following is the section of code where this would be done)
https://github.com/NathanKell/ModularFuelSystem/blob/master/Source/Tanks/ModuleFuelTanksRF.cs#L133

**Comment by blowfishpro** [comment] 2018-12-23 20:59
I'm traveling for about a week and a half.  Have access to my laptop but it's not my main mod dev computer.  Also not too familiar with the temperature code.  But I'll be back in the first few days of January, let me know if you need me to try and work it out then.

**Comment by Bornholio** [comment] 2019-01-08 02:44
RF for 1.4.5 indexed a bit ago, rf-v12.7.2

**Comment by Starwaster** [comment] 2019-01-12 01:22
I'm going to go ahead and close this now as 1.4.5 has been taken care of and 1.6.0 is going to happen pretty soonish. I've been running it through its paces in 1.6.1 and it seems solid except for a few GUI glitches that were

- in one case due to me copying unnecessary KSP/Unity dlls into the installation folder
- un-reproducible RF engine menu flickering

The only thing worth holding back on is going through the +30ish outstanding issues and seeing if I should address them in this release.

**Closed by Starwaster** 2019-01-12 01:22 UTC
