### ISSUE TITLE
Resource switching in flight

### ISSUE THREAD

**Issue by RealKolago** [NathanKell/ModularFuelSystem#126] opened 2015-12-23 21:52 UTC
With the concept of containers as versatile storage unit like in FTT 
https://github.com/BobPalmer/FTT
it would helpful to be able to reconfigure the storage in flight. 

I have seen this done in the WildBlueTools mod:
https://github.com/Angel-125/WildBlueTools
https://kerbalstuff.com/mod/947/WildBlueTools
Downside of this mod is the fixed mix of resources.

The Ultimate solution to this is your Modular Fuel System with in flight reconfiguration.
So we can fill up containers on demand with several resources in flight.

To change the resources in flight we need empty space. So if resources are consumed or dumped space gets available for reconfiguration to other resources.

Lets say we have a container configured with 1000 Monopropellant at the start. In flight the monopropellant gets (partly) consumed. No we have 500 MP and 500 empty tank space.
No we can reconfigure this empty space to hold Ore or something else useful.

**Comment by jbengtson** [comment] 2015-12-24 21:36
This is highly unrealistic and I oppose it on the grounds that it does not, in any way, fit into Real Fuels.  Tanks, pumps, piping, valves, etc... aren't built in a manner to allow such simple reconfiguration.

**Comment by NathanKell** [comment] 2015-12-24 22:21
This is a shared repo. RF probably wouldn't user the option but doesn't
mean MFT shouldn't.

Sent by my thumbs, slowly.

**Comment by RealKolago** [comment] 2015-12-24 22:21
Ok, Monopropelent is not the best example. But I talk about containers. What about food, supplies, RocketParts, metals, ore, Machinery, SpecializedParts, MaterialKits, Minerals and all that stuff you cant pump? To store this in a tank is highly unrealistic to.

**Comment by RealKolago** [comment] 2015-12-24 22:29
The cool thing about MFT is that we can config Tank Types and can avoid mixing pump able and other resources if we want.

**Comment by Starwaster** [comment] 2015-12-24 22:57
my thoughts on this: there are already mods that do what you want; I think the proper solution is provision for those resources (in a given part as managed by another mod or the player) to not be stored in an MFT config and to then be handled by another mod. 

There might be other possibilities; I'll put some thought into it.

**Comment by RealKolago** [comment] 2015-12-24 23:36
@Starwaster It didn't get your point. Which other mod does what I want? Provisioning for resources is ok but bringing less mass into orbit, that does the job, is key for rocket engineering. If I can use one versatile container with my interplanetary freighter instead of 3 than that is a desirable goal.

**Comment by NathanKell** [comment] 2015-12-27 06:00
This was, in fact, a long requested feature even for RF, so that for example Cygnus and ATV missions could be modeled (they take certain things up, and take garbage away). Let alone Dragon. Don't be too quick to cry Realismz!!1one, folks. :)

As for implementation, it's really not hard to make the GUI available in flight, the issue is properly handling non-empty tanks (i.e. do we make them untouchable? Do we allow shrinking to their current amount?) and making sure newly-added ones start unfilled.

**Comment by RealKolago** [comment] 2015-12-27 14:11
New tanks are emtpy.
Shrinking to their current amount, if you shrink beyond this a warning and confirm button that the content gets lost.
A tank config switch to make non-empty tanks untouchable. (this is feature is disabled by default)
Maybe a tank config switch to enable the new feature. So older tank configs don't change automatically.

**Comment by stratochief66** [comment] 2016-03-23 16:19
Poke @NathanKell long requested feature indeed. This would be very useful for ISRU missions. Bring LH2 to Mars in tanks, once the tanks are drained start filling them up with LO2 or LMethane. It would be nice if this could be implemented in RF in a realism friendly fashion :)

**Comment by Starwaster** [comment] 2019-08-06 00:42
Closing. Implementation #188 has issues that were not addressed when requested. If those are ever addressed by the implementer then maybe we'll take another look at it.

**Closed by Starwaster** 2019-08-06 00:42 UTC
