### ISSUE TITLE
Engines explode upon staging

### ISSUE THREAD

**Issue by Maxzhao1999** [NathanKell/ModularFuelSystem#180] opened 2017-03-17 12:23 UTC
using Ven's Revamp and real fuel stockalike config, my engines always explode immediately after shutdown and staging (no collision), however, this does not happen if staging happens when the engines are still running.

**Comment by Starwaster** [comment] 2017-03-17 21:18
I've seen this in solid fueled rockets and the cause is that the internal temperature jumps to an extremely high number. Probably the maximum possible value of a double. This is the RF internal engine temperature I'm referring to, not part.temperature.

**Comment by Maxzhao1999** [comment] 2017-03-17 23:30
But the is not solid fueled, HydroLOX and RP-1 seem to have the same problem.

**Comment by blowfishpro** [comment] 2017-03-17 23:35
No, but the issue could be related.

**Comment by Starwaster** [comment] 2017-03-19 01:31
Still trying to trace this. It's looking like a SolverEngines problem again.

Something interesting: If you use the ignore max temp cheat then the engines don't explode. That's not the interesting bit; they're coded to check for the cheat and not explode. The interesting bit is where they start throwing nullrefs until you turn the cheat off so they can go ahead and explode.

**Comment by Starwaster** [comment] 2017-03-26 02:11
Traced the problem to HERE:
https://github.com/NathanKell/ModularFuelSystem/blob/561b856d125cf90285813bee7c5fdfc0c654d199/Source/Engines/SolverRF.cs#L165
At the moment of decoupling, t0 is spiking badly. In one logged case where I put debugging info, t0 = ~1311380 (over 1.3 million Kelvin)

t0 can be further traced to EngineThermodynamics and is apparently stagnation temperature?

I think for now that should be taken out of the equation for setting non-combusting chamber temps because as it is now you can destroy an engine just by decoupling it, even standing on the launch pad.

**Comment by Starwaster** [comment] 2017-03-26 11:59
I am going to go ahead and close this out. The issue is resolved in the current build and there will be a release in the near future.

**Closed by Starwaster** 2017-03-26 11:59 UTC
